[package]
name = "xlsx-slx"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = "0.31.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { version = "1.37.0", features = ["full"] }
anyhow = "1.0.82"
